--- 
title: "R Lab for Regression Analysis"
author: |
  | Young-geun Kim
  | Department of Statistics, SKKU
  | \href{mailto: dudrms33@g.skku.edu}{dudrms33@g.skku.edu}
date: "`r format(Sys.time(), '%d %b, %Y')`"
site: bookdown::bookdown_site
documentclass: book
bibliography: [book.bib, packages.bib]
biblio-style: apalike
link-citations: yes
description: "This aims at covering materials of regression analysis with R programming."
---

# Linear Regression Analysis

```{r}
data(BioOxyDemand, package = "MPV")
(BioOxyDemand <-
  BioOxyDemand %>% 
  tbl_df())
```

## Relation

We wonder how `x` affects `y`, especially linearly.

- Functional relation: mathematical equation, $$y = \beta_0 + \beta_1 x$$
- Statistical relation: embeded with noise

So we try to estimate

$$y = \beta_0 + \beta_1 x + \epsilon$$

```{r}
BioOxyDemand %>% 
  ggplot(aes(x, y)) +
  geom_point()
```


Looking just with the eyes, we can see the linear relationship. Regression analysis estimates the relationship statistically.


```{r}
BioOxyDemand %>% 
  ggplot(aes(x, y)) +
  geom_smooth(method = "lm") +
  geom_point()
```





